### ISSUE TITLE
How do users add the preview image for posts, as shown on your demo site?

### ISSUE THREAD

**Issue by hawkins** [Kikobeats/uno-urban#10]
Hello, on your demo site, each post has a sort of preview image, show here:

![image](https://cloud.githubusercontent.com/assets/9123458/15805670/fcef1798-2af6-11e6-94bd-dd6e4953b72f.png)

How can users add these type images to our own writings? I could not find any related instructions in the documentation referenced from the sellfy page.

**Comment by hawkins** [comment]
My mistake. New to ghost and thought this was a theme-specific setting. For others not in the know, this can be accessed by visiting the content page in ghost settings, clicking the post, and then the cog in the top right. Then set the post image to whatever you like.

Thanks, and sorry for the accidentally irrelevant issue.

**Comment by Kikobeats** [comment]
you're welcome 👍
