### ISSUE TITLE
Error in gulp build-search

### ISSUE THREAD

**Issue by hpz24** [Kikobeats/uno-urban#11]
hi, 
i tried the new fulltext-search and get an error:
![image](https://cloud.githubusercontent.com/assets/818382/16443517/9b63e6b6-3dd9-11e6-8d18-551f9266f981.png)

**Comment by Kikobeats** [comment]
Hmmm looks like coffeescript loader failed.

Can you try this?

```
rm -rf node_modules && npm install
```

**Comment by hpz24** [comment]
hi,
after the command the build-search completes but...
![image](https://cloud.githubusercontent.com/assets/818382/16444514/a1c4ead2-3dde-11e6-9f5c-20587beba6cb.png)

i checked the entries in the search.json, as provided in your manual but they are seemed to be ok...

**Comment by Kikobeats** [comment]
That's my fault, JSON is malformed.

Copy and replace for this: https://gist.github.com/Kikobeats/fc1b8f667560e204abb4fbe13f4d3458

I'm going to release this into the next patch version, thanks!

**Comment by hpz24** [comment]
thanks for the new file!
so, with the new file the search starts, but the scripts reports, that in the sitemap is no url. when i open the sitemap-posts.xml in my browser, it works (there are urls)
![image](https://cloud.githubusercontent.com/assets/818382/16447302/1fe686de-3dec-11e6-9897-84cfbea8f5ee.png)

**Comment by Kikobeats** [comment]
strange... what version of Ghost are you running?

my command output:

```
gulp build-search
[11:30:44] Requiring external module coffee-script/register
[11:30:48] Using gulpfile ~/Projects/sailorjs.org/kikobeats.com/content/themes/Uno/gulpfile.coffee
[11:30:48] Starting 'build-search'...
[11:30:48] Finished 'build-search' after 6.14 ms
Welcome to "KIKOBLOG" algolia-webcrawler v1.0.1

Configuring your index kikoblog
Configured index properly

Parsing Sitemap https://kikobeats.com/sitemap-pages.xml
Registered https://kikobeats.com/about/
Registered https://kikobeats.com/
Sitemap https://kikobeats.com/sitemap-pages.xml registered 2 / 2 urls
Parsing Sitemap https://kikobeats.com/sitemap-posts.xml
Registered https://kikobeats.com/styleguide/
Registered https://kikobeats.com/http-post-dilemma/
...
```

settings of `search.json`:

```
"sitemaps": [
    { "url": "https://kikobeats.com/sitemap-posts.xml"},
    {"url": "https://kikobeats.com/sitemap-pages.xml"}
  ],
```

**Comment by hpz24** [comment]
hi, 
version ghost 0.8.0
maybe thereis a problem with the api-key from algolia? it is a little bit confusing, which api-key is the right one... in the backend i use the "Admin API-Key", in the frontend "search-only API-Key"

but i´m worry about my Reverse Proxy, i think there will be the problem...
