### ISSUE TITLE
Markdown isn't working properly

### ISSUE THREAD

**Issue by stylersnico** [Kikobeats/uno-urban#13]
Hi,

I try to have code to a post here: https://enter.thewhiterabbit.space/create-a-ecdsa-certificate-with-lets-encrypt/

The preview is working perfectly in editor but the code isn't forming properly on the final view.

Any idea why ?

Thanks,

**Comment by stylersnico** [comment]
Hi,

I've got it using Prism.js but I simply doesn't want to use that thing.

I want to use the markdown formatting of ghost, the Github one, why he isn't working?

Thanks

**Comment by stylersnico** [comment]
I don't get it.

Why : 

'code' 

and

'''
code
'''

are not working and why only (per example)

'''bash
code
'''

works ?

Thanks

**Comment by Kikobeats** [comment]
Hello!

First of all, docs about hightlight code: https://kikobeats.github.io/uno-urban/customization/highlight-code.html

Second, the correct markdown syntax for the code is:

<img width="182" alt="screen shot 2016-07-21 at 20 18 49" src="https://cloud.githubusercontent.com/assets/2096101/17033855/5d2f666e-4f80-11e6-8a4c-cdf965cb6771.png">

The default prism theme is similar to GitHub, you can check it in the [styleguide](https://kikobeats.com/styleguide/).

**Comment by stylersnico** [comment]
Hello,

The docs doesn't explain how to compile to whole thing and how to use it in a post.

And yes I know for the ' alternative, that was for displaying it directly on Github without a screenshot :)

However, the code in your screenshot should work without "js" according to ghost documentation:
http://support.ghost.org/markdown-guide/
