### ISSUE TITLE
Change cover and sidebar elements color ?

### ISSUE THREAD

**Issue by Frantxi** [Kikobeats/uno-urban#14]
# General comment

Hey Kikobeats,
I just bought your template (thanks! it looks good) and was wondering how to change  the color of the elements of the cover page and sidebar.  

Thanks for the help!

**Comment by Kikobeats** [comment]
Hey!

For edit the default styles of the theme is necessary basic web development skills.

Check the color section in the documentation: https://kikobeats.github.io/uno-urban/customization/colors.html

If you have any question, feel free to reply 😄
