### ISSUE TITLE
No logo

### ISSUE THREAD

**Issue by Setsuneh** [Kikobeats/uno-urban#15]
Hi,

I've a problem with the new version. No logo at the index.
## Environment Settings
- Theme version: uno-urban - 3.3.7
- Browser: Vivaldi
- OS: Browser Windows 10 - Website: Debian 8.6
- Website: cyprius.fr 

Thanks :)

**Comment by Setsuneh** [comment]
Fix thanks :)

**Comment by Kikobeats** [comment]
👍
