### ISSUE TITLE
Highlight over post images, blinks

### ISSUE THREAD

**Issue by jdchandler** [Kikobeats/uno-urban#17]
# General comment
my blog - http://www.justinchandler.blog

Just purchased this theme and I love it. One thing I noticed from your demo page, as I hover over my post images, as you slowly move the cursor DOWN, it seems to only highlight at certain parts of the box where yours is highlight no matter where your cursor is in the box. Notice how it blinks as you slowly move cursor down the page.

## Environment Settings

**Code Injection:**

**HEAD:**
<script>
var disqus_shortname = 'justinchandler';
</script>
<script>
var posts_headline = 'Thoughts, Stories, Ideas.';
</script>

**FOOT:**
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.1.6/zepto.min.js"></script>
<script>jQuery = Zepto</script>

- Theme version: 3.3.7
- Browser: Google Chrome Version 56.0.2924.87 (64-bit)
- OS: Windows 10 Anniversary Update

*For know theme version, open devtools in your browser and type `Uno.version`*

### Expected Behavior
As cursor is on a specific post, that post highlights with brighter color
### Actual Behavior
As cursor is on specific post, only specific spots highlight the post image with brighter color
### Steps to reproduce the behavior
Notice how each post image blinks as you slowly move cursor down the page.

**Comment by jdchandler** [comment]
Steps to reproduce:

1. Open home page
2. Click Posts
3. Notice highlighting works good
4. Click any post
5. Click Home on left sidebar
6. Click Posts
7. Notice highlight bug

**Comment by Kikobeats** [comment]
Hmmm can you provide a gif?

**Comment by jdchandler** [comment]
https://www.useloom.com/share/2f1e9a96bf5844d09a7e665159d96df0

**Comment by Kikobeats** [comment]
I remember handle this, but yep, looks buggy, thanks for the report :)

**Comment by franklouwers** [comment]
This same problem causes the search to stop to work btw. 

I see the following errors in the error console (but my Javascript skills are 0, so can't help):

```
[Error] ReferenceError: Can't find variable: algoliasearch


[Error] TypeError: a.postMessage is not a function. (In 'a.postMessage(b,c)', 'a.postMessage' is undefined)
```

**Comment by Kikobeats** [comment]
This bug will be fixed this week under the new v4 version compatible with Ghost 1.x 👍

**Comment by Kikobeats** [comment]
Thanks for your reporting, it should be fixed at v4.0.0. 

It is now avaiable at sellfy, please use it under Ghost 1.x and tell me if you have any issue 😄 .

**Comment by franklouwers** [comment]
Hi Kiko,

Is it only 1.x compat, or should a recent 0.x work as well?

**Comment by Kikobeats** [comment]
I released the fix under `4.0.0`, so you need Ghost v1.

I did that because sellfy only provide me a way to publish one version all the time (the latest).

If you need to work with Ghost 0.x, give an email and I provide you the last Ghost 3.x patch 😄

**Comment by franklouwers** [comment]
Hi Kiko,

Nah, I'll first upgrade to 1.x, it was on my todo list anyway :)

**Comment by Kikobeats** [comment]
haha, yes, it's a little tidious but it's better
