### ISSUE TITLE
Future for Uno-Urban?

### ISSUE THREAD

**Issue by jdchandler** [Kikobeats/uno-urban#22]
Will there be any bug-fixes or enhancements done to this theme ever or is it pretty much dead?

Ghost 1.0 is coming out, will this be compatible?
Are you working on any 1.0 themes?

**Comment by Kikobeats** [comment]
Hey,

This theme is almost 100% compatible with Uno 1.0.0.

After the the final release of Ghost, I will update and fix some minor issues with the theme.
