### ISSUE TITLE
Ghost(Pro) theme upload generates errors

### ISSUE THREAD

**Issue by EweSparky** [Kikobeats/uno-urban#24]
# General comment

When uploading this theme to Ghost(Pro), the following import errors are thrown:

**Invalid theme**

- Fatal Errors (Must-fix to activate theme)
  - Replace the {{image}} helper with {{img_url feature_image}} or {{img_url profile_image}}
    - Affected files:
      - index.hbs: Please remove or replace {{image}} from this template
      - page.hbs: Please remove or replace {{image}} from this template
      - post.hbs: Please remove or replace {{image}} from this template
      - tag.hbs: Please remove or replace {{image}} from this template
  - Replace the {{author.image}} helper with {{author.profile_image}}
    - Affected files:
      - partials/post-author.hbs: Please remove or replace {{author.image}} from this template
  - Replace the {{@blog.cover}} helper with {{@blog.cover_image}}
    - Affected files:
      - error.hbs: Please remove or replace {{@blog.cover}} from this template
      - partials/aside.hbs: Please remove or replace {{@blog.cover}} from this template
  - Replace the {{#if image}} helper with {{#if feature_image}}, or {{#if profile_image}}
    - Affected files:
      - page.hbs: Please remove or replace {{#if image}} from this template
      - post.hbs: Please remove or replace {{#if image}} from this template

## Environment Settings

*Necessary if you want to report a bug*

- Theme version: 3.3.7
- Browser: Firefox 54.0.1
- OS: Windows 10 Pro 15063.502

*For know theme version, open devtools in your browser and type `Uno.version`*

### Expected Behavior

Theme imports successfully without error.

### Actual Behavior

Above error messages generated during import, preventing the theme from uploading without the issues in question being rectified first.

### Steps to reproduce the behavior

Drag theme .zip on the theme uploader window in the Ghost(Pro) design tab.

**Comment by Kikobeats** [comment]
Thanks for the feedback!

Currently I'm updatin the theme to be compatible with 1.0 version.

Hope release a new version this week 😄

**Comment by Kikobeats** [comment]
v4.0.0 released at sellfy, please use it under Ghost 1.x and tell me if you have any issue 😄 .

**Comment by EweSparky** [comment]
All good! Thanks for the quick turnaround.
