### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by Kamasoutra** [Kikobeats/uno-urban#25]
Hi there,

I've juste upgraded everything to the latest versions and it seems that images are shown in full size in posts.

**Comment by Kikobeats** [comment]
Can you provide the link of your blog?

**Comment by Kamasoutra** [comment]
Sure, try [https://jp.palik.fr/boite-a-outils-ncdu/](https://jp.palik.fr/boite-a-outils-ncdu/)

**Comment by Kikobeats** [comment]
Thanks, looks like was a little problem with the Ghost 1.x migration.

Currently fixed at 4.0.1, avaiable at sellfy: https://sellfy.com/p/G5kK/

Can you confirm to me all is working fine now? 😄

**Comment by Kamasoutra** [comment]
Perfect, everything is back to normal 👍 

Thanks Dude !
