### ISSUE TITLE
Homepage problems. Theme broken

### ISSUE THREAD

**Issue by ghost** [Kikobeats/uno-urban#28]
Hi,

I bought this theme today. Please bear with me as I'm not much of a pro at using Ghost.

Firstly. The Demo on your site doesn't seem to be the same theme from what I can see, or at least it doesn't look that way for me. Is it still the same? If it isn't you should consider removing the demo link so people don't get confused.

I added this code into the footer on the "Code Injection" page as I don't have any plugins installed. It didn't really seem to matter which version of this jQuery string I used anyway as neither makes the site page work properly:

`<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>`

My blog is available here: [blog link](https://www..com)
_Bear it mind though that depending on how long it takes to get an answer. I may have reverted to using another them because this one doesn't work_ So please see this: [screenshot](https://i.imgur.com/78Cksvs.jpg)

Basically as you can see I have no posts showing for some reason. Also if you click the Home button or reload the page. You can see the blog style change quickly whilst the page is being refreshed (presumably before the footer code is loaded). This looks really ugly.

Additionally, it seems that your social media buttons are visible at the top of my page. The buttons link to your social media accounts. How do I remove/change these to my own? I don't see an option to do this anywhere and changing the social options in the Ghost admin panel doesn't overwrite them with my own links.

I'm hoping that there's just something I need to change and that the theme isn't actually broken. I'd like to get it as close to the demo photos on the selly page.

Please let me know if I need to provide any more information. I have no idea how long it'll take for a reply, so I'll leave this issue up for a few days but if I don't get one within a reasonable time-frame I'll request a refund. I hope you understand.

**Comment by Kikobeats** [comment]
my current website doesn't represent the `uno-urban` theme; However, you can see how it looks based on the screenshots.

I recommend you experiment a bit with the Ghost platform and then apply the theme.

Check your devTools as well; looks like you have an error related with the search engine used by theme that is blocking the expected flow.

No problem if you want to request a refund.

**Comment by ghost** [comment]
I think it's obvious the theme is broken. I've got a few themes installed and none of them have the author's social media links built into the theme, or cause an really ugly refresh when the page is refreshed. 

I've read the documentation and style page but there's nothing useful there. The theme doesn't look like the screenshots show and it doesn't behave like shown on other sites. Also the screenshots aren't really big enough to show your customers how it's meant to look in the first place. 

I got it because I figured it would still work out of the box and that you were actively developing it, but I guess not.

So I'd like a refund please. I think there's too many inconsistencies and if the demo on your site isn't the uno theme and it requires in-depth tinkering to remove your social links or fix issues with the search engine. That's false advertising in my opinion. I didn't pay to have to fix the layout myself.
