### ISSUE TITLE
Unable to perform bower install

### ISSUE THREAD

**Issue by hawkins** [Kikobeats/uno-urban#9]
Hello, upon attempting installation of your theme, I encounter the following error on `bower install`:

![image](https://cloud.githubusercontent.com/assets/9123458/15803501/b4baa1d6-2aa6-11e6-8624-c3bf42154299.png)

Any ideas what went wrong here?

**Comment by Kikobeats** [comment]
yes, but no problem, actually linkify dependency is not used, I'm going to move out of the bower file. Thanks for the report! 👍

**Comment by Kikobeats** [comment]
I'm preparing the new patch release 😄
